import { useEffect, useMemo, useState } from 'react'
import { api } from '../api/client.js'
import { Icon } from '../components/Icons.jsx'

export default function ModelCenter() {
  const [data,setData]=useState(null); const [error,setError]=useState('')
  useEffect(()=>{api.modelReport().then(setData).catch(e=>setError(e.message))},[])
  const models=useMemo(()=>data?.models?Object.entries(data.models).sort((a,b)=>b[1].cv_roc_auc-a[1].cv_roc_auc):[],[data])
  if(error) return <div className="empty-panel"><h3>Model details unavailable</h3><p>{error}</p></div>
  const c=data?.calibrated_holdout
  return <div className="page-stack">
    <section className="model-hero"><div><span className="section-kicker">SELECTED MODEL</span><h2>{data?.selected_model || 'Loading model details…'}</h2><p>{data?.selection_rule || 'Loading performance details…'}</p></div><div className="model-hero__badge"><span>DECISION POINT</span><strong>{data?.threshold ?? '—'}</strong></div></section>
    <section className="metric-strip metric-strip--model"><article><span className="metric-strip__icon"><Icon name="activity"/></span><div><small>ROC-AUC</small><strong>{c?.roc_auc?.toFixed(4)||'—'}</strong></div></article><article><span className="metric-strip__icon"><Icon name="check"/></span><div><small>Accuracy</small><strong>{c?`${(c.accuracy*100).toFixed(1)}%`:'—'}</strong></div></article><article><span className="metric-strip__icon"><Icon name="pulse"/></span><div><small>Recall</small><strong>{c?`${(c.recall*100).toFixed(1)}%`:'—'}</strong></div></article><article><span className="metric-strip__icon"><Icon name="brain"/></span><div><small>F1 score</small><strong>{c?.f1?.toFixed(4)||'—'}</strong></div></article></section>
    <div className="model-center-grid"><section className="panel panel--wide"><div className="panel-head"><div><span className="section-kicker">MODEL COMPARISON</span><h3>Cross-validation performance</h3></div></div><div className="leaderboard">{models.map(([name,m],i)=><div className={`leaderboard-row ${i===0?'winner':''}`} key={name}><div className="leaderboard-rank">{i+1}</div><div className="leaderboard-name"><strong>{name}</strong><small>{i===0?'Selected model':'Compared model'}</small></div><div className="leaderboard-bar"><span style={{width:`${m.cv_roc_auc*100}%`}}/></div><strong>{m.cv_roc_auc.toFixed(4)}</strong><div className="leaderboard-holdout"><small>Test AUC</small><span>{m.holdout.roc_auc.toFixed(4)}</span></div></div>)}</div></section>
    <section className="panel"><div className="panel-head"><div><span className="section-kicker">TEST RESULTS</span><h3>Prediction breakdown</h3></div></div>{c?.confusion_matrix&&<div className="confusion"><div/><div className="axis">Predicted absent</div><div className="axis">Predicted present</div><div className="axis">Actual absent</div><div className="cell tn"><strong>{c.confusion_matrix[0][0]}</strong><span>Correctly absent</span></div><div className="cell fp"><strong>{c.confusion_matrix[0][1]}</strong><span>False positive</span></div><div className="axis">Actual present</div><div className="cell fn"><strong>{c.confusion_matrix[1][0]}</strong><span>False negative</span></div><div className="cell tp"><strong>{c.confusion_matrix[1][1]}</strong><span>Correctly present</span></div></div>}</section>
    <section className="panel"><div className="panel-head"><div><span className="section-kicker">TRAINING DETAILS</span><h3>Data split</h3></div></div><div className="audit-list"><div><span>Training records</span><strong>{data?.split?.train_rows||'—'}</strong></div><div><span>Test records</span><strong>{data?.split?.test_rows||'—'}</strong></div><div><span>Balanced split</span><strong>{data?.split?.stratified?'Yes':'—'}</strong></div><div><span>Random seed</span><strong>{data?.split?.random_state??'—'}</strong></div><div><span>Training profile</span><strong>{data?.training_mode === 'full' ? 'Full training' : data?.training_mode === 'fast' ? 'Quick training' : '—'}</strong></div></div></section></div>
    <div className="safety-banner"><Icon name="info"/><div><strong>About these results</strong><p>{data?.cautions?.[0] || 'HeartTrack is not a diagnostic tool, and its predictions have not been clinically validated.'}</p></div></div>
  </div>
}
