import { useEffect, useState } from 'react'
import { api } from '../api/client.js'
import { Icon } from '../components/Icons.jsx'

export default function SystemHealth(){
 const [health,setHealth]=useState(null); const [latency,setLatency]=useState(null); const [checked,setChecked]=useState(null)
 async function refresh(){const start=performance.now();try{const h=await api.health();setHealth(h);setLatency(Math.round(performance.now()-start));setChecked(new Date())}catch{setHealth({status:'down',model_ready:false})}}
 useEffect(()=>{refresh()},[])
 return <div className="page-stack"><section className="system-hero"><div className={`system-orb ${health?.status==='ok'?'online':''}`}><span/></div><div><span className="section-kicker">SYSTEM STATUS</span><h2>{health?.status==='ok'?'Everything is operating normally':'Checking system status…'}</h2><p>Review connection, prediction, and privacy status at a glance.</p></div><button className="btn btn--ghost" onClick={refresh}>Check again</button></section><section className="metric-strip"><article><span className="metric-strip__icon"><Icon name="activity"/></span><div><small>Connection</small><strong>{health?.status==='ok'?'Online':'Checking'}</strong></div></article><article><span className="metric-strip__icon"><Icon name="brain"/></span><div><small>Prediction model</small><strong>{health?.model_ready?'Available':'Checking'}</strong></div></article><article><span className="metric-strip__icon"><Icon name="pulse"/></span><div><small>Response time</small><strong>{latency!==null?`${latency} ms`:'—'}</strong></div></article><article><span className="metric-strip__icon"><Icon name="shield"/></span><div><small>Saved on device</small><strong>No</strong></div></article></section><div className="system-grid"><section className="panel panel--wide"><div className="panel-head"><div><span className="section-kicker">HOW IT WORKS</span><h3>From assessment to result</h3></div></div><div className="architecture-flow">{[['user','Assessment','Collects the information you enter'],['shield','Secure session','Protects your sign-in'],['activity','Data review','Checks the assessment values'],['brain','Prediction model','Calculates the risk estimate'],['pulse','Result','Shows probability and key factors']].map(([icon,title,note],i)=><div className="arch-node" key={title}><span><Icon name={icon}/></span><strong>{title}</strong><small>{note}</small>{i<4&&<i>→</i>}</div>)}</div></section><section className="panel"><div className="panel-head"><div><span className="section-kicker">PRIVACY</span><h3>What HeartTrack does not keep</h3></div></div><div className="check-list">{['Assessment entries after a refresh','Previous results after a refresh','Sign-in details on this device','Temporary account data after a restart'].map(x=><div key={x}><span><Icon name="check" size={14}/></span><p>{x}</p></div>)}</div></section><section className="panel system-runtime-panel"><div className="panel-head"><div><span className="section-kicker">CURRENT STATUS</span><h3>Latest check</h3></div></div><div className="audit-list"><div><span>Application</span><strong>HeartTrack</strong></div><div><span>Status</span><strong>{health?.status === 'ok' ? 'Online' : health?.status === 'down' ? 'Unavailable' : '—'}</strong></div><div><span>Prediction model</span><strong>{health?.model_ready?'Available':'Unavailable'}</strong></div><div><span>Last checked</span><strong>{checked?checked.toLocaleTimeString():'—'}</strong></div></div></section></div></div>
}
